### ISSUE TITLE
Failure due to OtpDetails link required

### ISSUE THREAD

**Issue by duckworth** [robinvandernoord/lib2fas-python#2]
The type OtpDetails has link as required causing an error:
`configuraptor.errors.ConfigErrorMissingKey: Config key 'link' (type `str`) of class `OtpDetails` was not found in the config, but is required as a default value is not specified.`

None of my exported entries have a link (they were imported from Authy if that matters) but they work fine in the 2FAS app.

**Comment by robinvandernoord** [comment]
Thank you for reporting this. I also imported my entries from authy, so that's odd. I'll look into this soon!

**Comment by robinvandernoord** [comment]
Oops, I didn't mean to close the issue. I have written a commit that should make those fields optional, based on the official 2fas model in kotlin ([twofas/2fas-android:prefs/src/main/java/com/twofasapp/prefs/model/RemoteService.kt](https://github.com/twofas/2fas-android/blob/develop/prefs/src/main/java/com/twofasapp/prefs/model/RemoteService.kt)), but I haven't published a patch release yet because I want to test it some more first.

**Comment by duckworth** [comment]
Just pulled the latest and tried it on my backup file and it worked! Thanks.

**Comment by robinvandernoord** [comment]
Thanks for trying it out. This issue should be fixed in 0.1.4
